/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package playu_two.newpackage;
import java.util.regex.Pattern;
import java.sql.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.*;
/**
 *
 * @author HP
 */
public class Sell extends javax.swing.JFrame {

    /**
     * Creates new form Sell
     */
    public Sell() {
        initComponents();
    }
        Connection con;
        PreparedStatement pst;
        ResultSet rs;
        
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_sell = new javax.swing.JButton();
        txt_pname = new javax.swing.JTextField();
        txt_pprice = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btn_add = new javax.swing.JButton();
        btn_odd = new javax.swing.JButton();
        txt_pque = new javax.swing.JTextField();
        cmb_cate = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btn_cls = new javax.swing.JButton();
        lbl_vpname = new javax.swing.JLabel();
        lbl_vquan = new javax.swing.JLabel();
        lbl_vprice = new javax.swing.JLabel();
        lbl_vcat = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        lbl_type = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);
        setType(java.awt.Window.Type.UTILITY);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(750, 500));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Product Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Quantity");

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Price");

        btn_sell.setBackground(new java.awt.Color(0, 255, 153));
        btn_sell.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        btn_sell.setForeground(new java.awt.Color(255, 255, 255));
        btn_sell.setText("SELL");
        btn_sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sellActionPerformed(evt);
            }
        });

        txt_pname.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_pprice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel13.setBackground(java.awt.Color.white);
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Sell Item");
        jLabel13.setEnabled(false);
        jLabel13.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel13.setPreferredSize(new java.awt.Dimension(80, 80));

        btn_add.setBackground(new java.awt.Color(51, 0, 204));
        btn_add.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_add.setForeground(new java.awt.Color(255, 255, 255));
        btn_add.setText("+");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_odd.setBackground(new java.awt.Color(204, 0, 0));
        btn_odd.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        btn_odd.setForeground(new java.awt.Color(255, 255, 255));
        btn_odd.setText("-");
        btn_odd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_oddActionPerformed(evt);
            }
        });

        txt_pque.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmb_cate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmb_cate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Electric", "Sports", "Fashion" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Category");

        btn_cls.setBackground(new java.awt.Color(255, 51, 102));
        btn_cls.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        btn_cls.setForeground(new java.awt.Color(255, 255, 255));
        btn_cls.setText("CLEAR");
        btn_cls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clsActionPerformed(evt);
            }
        });

        lbl_vpname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_vpname.setForeground(new java.awt.Color(255, 51, 51));

        lbl_vquan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_vquan.setForeground(new java.awt.Color(255, 51, 51));

        lbl_vprice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_vprice.setForeground(new java.awt.Color(255, 51, 51));

        lbl_vcat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbl_vcat.setForeground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_vcat, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                            .addComponent(lbl_vquan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_vprice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_pque, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(btn_odd))
                            .addComponent(cmb_cate, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pprice, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_pname, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_vpname, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btn_sell, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btn_cls, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vpname)
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_odd, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_pque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_vquan)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_pprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_vprice)
                .addGap(7, 7, 7)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmb_cate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(lbl_vcat)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_sell)
                    .addComponent(btn_cls))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 380));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(750, 500));

        jLabel10.setBackground(java.awt.Color.white);
        jLabel10.setFont(new java.awt.Font("Forte", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Play");
        jLabel10.setEnabled(false);
        jLabel10.setMaximumSize(new java.awt.Dimension(100, 100));
        jLabel10.setPreferredSize(new java.awt.Dimension(80, 80));

        jLabel11.setFont(new java.awt.Font("Snap ITC", 0, 45)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 0, 102));
        jLabel11.setText("U");

        btn_back.setBackground(new java.awt.Color(255, 51, 51));
        btn_back.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("BACK");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });

        lbl_type.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_back, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(lbl_type, javax.swing.GroupLayout.PREFERRED_SIZE, 1, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(222, 222, 222)
                .addComponent(lbl_type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_back)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 141, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
       String a = txt_pque.getText();
       int b = Integer.parseInt(a);
       b = b+1;
       txt_pque.setText(Integer.toString(b));
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_oddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_oddActionPerformed
       String a = txt_pque.getText();
       int b = Integer.parseInt(a);
       b = b-1;
       txt_pque.setText(Integer.toString(b));
    }//GEN-LAST:event_btn_oddActionPerformed

    private void btn_sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sellActionPerformed
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/playu","root","");
            
        if(txt_pname.getText().isEmpty() || Pattern.matches("^[0-9]+",txt_pname.getText()) || Pattern.matches(".*[0-9].*",txt_pname.getText()))
        {
            lbl_vpname.setText("Cannot be empty or Cannot be enter nubmer for name");
        }
        else if(txt_pque.getText().isEmpty() || Pattern.matches("^[a-zA-Z]+",txt_pque.getText()) || Pattern.matches(".*[a-zA-Z].*",txt_pque.getText()))
        {
            lbl_vquan.setText("Cannot be empty or Cannot be enter letter for quantity");
        }
        else if(txt_pprice.getText().isEmpty() || Pattern.matches("^[a-zA-Z]+",txt_pprice.getText()) || Pattern.matches(".*[a-zA-Z].*",txt_pprice.getText()))
        {
           lbl_vprice.setText("Cannot be empty or Cannot be enter letter for price");
        }
        else if(cmb_cate.getSelectedIndex() == 0 || cmb_cate.getSelectedIndex() != 1 || cmb_cate.getSelectedIndex() != 2 || cmb_cate.getSelectedIndex() != 3 )
        {
           lbl_vcat.setText("First select category type");
        }
        else
        {
                switch (cmb_cate.getSelectedIndex()) {
                    case 1:
                        {
                            lbl_type.setText("Electric");
                            String query = "insert into item(item_name,item_quantity,item_price,item_category) values(?,?,?,?)";
                            pst = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
                            pst.setString(1,txt_pname.getText());
                            pst.setString(2,txt_pprice.getText());
                            pst.setString(3,txt_pque.getText());
                            pst.setString(4,lbl_type.getText());
                            pst.executeUpdate();
                            break;
                        }
                    case 2:
                        {
                            lbl_type.setText("Sports");
                            String query = "insert into item(item_name,item_quantity,item_price,item_category) values(?,?,?,?)";
                            pst = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
                            pst.setString(1,txt_pname.getText());
                            pst.setString(2,txt_pprice.getText());
                            pst.setString(3,txt_pque.getText());
                            pst.setString(4,lbl_type.getText());
                            int a=pst.executeUpdate();
                            if(a == 1)
                            {
                                JOptionPane.showMessageDialog(this,"Selling Successful","Success",JOptionPane.INFORMATION_MESSAGE);
                            }
                            else if(a==0)
                            {
                                JOptionPane.showMessageDialog(this,"Can't add item","Error",JOptionPane.ERROR_MESSAGE);
                            }               break;
                        }
                    case 3:
                        {
                            lbl_type.setText("Fashion");
                            String query = "insert into item(item_name,item_quantity,item_price,item_category) values(?,?,?,?)";
                            pst = con.prepareStatement(query,Statement.RETURN_GENERATED_KEYS);
                            pst.setString(1,txt_pname.getText());
                            pst.setString(2,txt_pprice.getText());
                            pst.setString(3,txt_pque.getText());
                            pst.setString(4,lbl_type.getText());
                            int a= pst.executeUpdate();
                            if(a == 1)
                            {
                                JOptionPane.showMessageDialog(this,"Selling Successful","Success",JOptionPane.INFORMATION_MESSAGE);
                            }
                            else if(a==0)
                            {
                                JOptionPane.showMessageDialog(this,"Can't add item","Error",JOptionPane.ERROR_MESSAGE);
                            }               break;
                        }
                    default:
                        break;
                }
        }
        }
        catch(ClassNotFoundException | SQLException ex)
        {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_btn_sellActionPerformed

    private void btn_clsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clsActionPerformed
       
        txt_pname.setText("");
        txt_pprice.setText("");
        txt_pque.setText("");
        cmb_cate.setSelectedIndex(0);
        lbl_vcat.setText("");
        lbl_vpname.setText("");
        lbl_vquan.setText("");
        lbl_vprice.setText("");
    }//GEN-LAST:event_btn_clsActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        User_Menu obj = new User_Menu();
        obj.show();
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sell().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_cls;
    private javax.swing.JButton btn_odd;
    private javax.swing.JButton btn_sell;
    private javax.swing.JComboBox<String> cmb_cate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_type;
    private javax.swing.JLabel lbl_vcat;
    private javax.swing.JLabel lbl_vpname;
    private javax.swing.JLabel lbl_vprice;
    private javax.swing.JLabel lbl_vquan;
    private javax.swing.JTextField txt_pname;
    private javax.swing.JTextField txt_pprice;
    private javax.swing.JTextField txt_pque;
    // End of variables declaration//GEN-END:variables
}
